server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
    initialization-mode: always
  sql:
    init:
      schema-locations:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: "*"